# Generated by Django 2.1.4 on 2020-04-08 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected', models.IntegerField(default=0)),
                ('death', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('district', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedCoronaCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fb_link', models.CharField(max_length=265)),
                ('affected', models.IntegerField(default=0)),
                ('death', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('district', models.CharField(max_length=265)),
                ('source', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('2', 'Pending'), ('1', 'Accept'), ('0', 'Cancel')], default='2', max_length=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
