# Generated by Django 2.1.4 on 2020-04-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_auto_20200408_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronacase',
            name='district',
            field=models.CharField(max_length=265),
        ),
    ]
