# Generated by Django 2.1.4 on 2020-04-07 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedcoronacase',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corona.District'),
        ),
    ]
