# Generated by Django 2.1.4 on 2020-04-09 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_auto_20200408_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronacase',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coronacase',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submittedcoronacase',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submittedcoronacase',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
