# Generated by Django 2.1.4 on 2020-04-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_auto_20200407_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedcoronacase',
            name='status',
            field=models.CharField(choices=[('2', 'Pending'), ('1', 'Success'), ('0', 'Cancel')], default='2', max_length=1),
        ),
    ]
